### ISSUE TITLE
Reducer state location

### ISSUE THREAD

**Issue by camwest** [cloudflare/cf-ui#10]
I noticed in the card builder this project assumes state.cards is where the reducer is mounted. Is this a safe assumption?

I'm having a similar problem in my own codebase and I wonder if there are better strategies then expecting state to be in a specific spot.

I feel like this breaks encapsulation because it forces you to mount the component at the top of the state tree in a well known location. 

Any ideas?

**Comment by camwest** [comment]
For reference I'm talking about mapStateToProps here https://github.com/cloudflare/cf-ui/blob/master/packages/cf-builder-card/src/CardBuilder.js

**Comment by thejameskyle** [comment]
Yes it's a required location, I know it's kinda gross, but I couldn't come up with something better.

**Comment by camwest** [comment]
@thejameskyle the only thing I can think of is having a map of state locations in another reducer. But then you'd still need 1 well known location but it would be more scalable.

**Comment by thejameskyle** [comment]
I don't think CloudFlare will ever run into scaling issues with this

**Comment by camwest** [comment]
@thejameskyle Yeah scalable isn't the right word. It's just the implicit API that makes it harder to re-use components with reducers since you need to "set it up" properly. It means if I use the project but I also happen to have another piece of state in that location I've got a problem.

**Comment by camwest** [comment]
@gaearon any recommendations on what the best approach is for "third party reducers" that also have mapStateToProps which need to get access to the state the reducer is producing?

**Comment by tajo** [comment]
We will remove redux stuff from cf-builders. https://github.com/cloudflare/cf-ui/issues/105
