### ISSUE TITLE
Publish with --only-explicit-updates

### ISSUE THREAD

**Issue by wyuenho** [cloudflare/cf-ui#110]
Lerna allows publishing [only explicitly updated](https://github.com/cloudflare/cf-ui/pull/59/files) packages instead of it and all the packages that depend on it, and all the packages that depend on the the dependencies at infinitum.

This is nice since there are so many packages in cf-ui and the inter-dependency graph is very intricate. It's doesn't seem to make sense to have a new version of `cf-component-button`, if every code change happened in say `cf-style-const`.

A concern was raised by @tajo that if a UI component changes its layout that affect their users, e.g. cf-component-table renders divs instead of table components, such that cf-builder-table renders completely differently now. cf-builder-table should be automatically get a version bump during publishing too, even when no code has changed in the builder. I would argue this is still an invalid argument because this should never happen. If cf-component-table changes the layout, and breaks cf-builder-table, cf-component-table should get a major version bump so no consumers will be broken.

Thoughts?

**Comment by jwineman** [comment]
Is there a use case outside of `cf-builder-` components?  If we end up deprecating those because we don't use them then there is no reason not to use `--only-explicit-updates` right?

**Comment by sejoker** [comment]
>If the cf-component-table changes the layout, and breaks cf-builder-table, cf-component-table should get a major version bump so no consumers will be broken.

Agree, with amount of packages we have at the moment release without `--only-explicit-updates` looks unmanageable for me.

**Comment by jwineman** [comment]
https://github.com/lerna/lerna#--only-explicit-updates
> It will update the versions in dependencies without publishing new versions of them

This is the root of @tajo's publish problems earlier

**Comment by sejoker** [comment]
I see, that's dangerous, @jwineman thanks for pointing this out.

**Comment by tajo** [comment]
`--only-explicit-updates` is being removed: https://github.com/lerna/lerna/pull/707

**Comment by tajo** [comment]
Closing since `--only-explicit-updates` doesn't exist anymore.
