### ISSUE TITLE
Latest release of fela broke our tests

### ISSUE THREAD

**Issue by sejoker** [cloudflare/cf-ui#112]
What happened:

Fela released a [new version](https://github.com/rofrischmann/fela/releases/tag/4.3.1) (2 hours ago) which broke 11 tests.
Tests pass on version 4.2.6.

Solution:
lock dependencies with yarn. Upgrade dependencies through PR.

<img width="831" alt="screen shot 2017-03-22 at 12 51 47 pm" src="https://cloud.githubusercontent.com/assets/125466/24198581/5ab4936c-0efe-11e7-8656-a70d00ace399.png">

**Comment by wyuenho** [comment]
Run `npm run update-snapshots`

**Comment by sejoker** [comment]
that's not a long term solution, that's a reaction to the problem of unexpected changes. I spent extra hour finding the root cause of the failed tests.

**Comment by tajo** [comment]
Yea, this is probably going to happen often that fela releases a new version, some style rendering changes and it breaks classNames in snapshots. That should not be a big concern.

**Comment by sejoker** [comment]
@tajo after https://github.com/cloudflare/cf-ui/issues/114 was merged it's not a big concern anymore.
