### ISSUE TITLE
cf-util-http API incompatible change 

### ISSUE THREAD

**Issue by sejoker** [cloudflare/cf-ui#129]
with latest release 3.5.0 of `cf-util-http` we introduced breaking change in the API. Now we use default params for opts https://github.com/cloudflare/cf-ui/blob/master/packages/cf-util-http/src/http.js#L107. This is a problematic, because it will set default value if only `undefined` is passed. The previous versions worked with `null` just fine, but now passing `null` value breaks on the first line https://github.com/cloudflare/cf-ui/blob/master/packages/cf-util-http/src/http.js#L108, because opts is null. 

Proposal: release fix for 3.5.1 which allow null in the meantime. Default params change is semver major. We should allow gradual upgrade path.

**Comment by wyuenho** [comment]
The root cause of that is that param should never be required in the first place. I can go back treating null as undefined. Do we have places that still use null?

**Comment by sejoker** [comment]
I hope not any more, but you never know for sure.

**Comment by wyuenho** [comment]
Well, partners is still bound to 3.0.0, so when they upgrade they'll have to fix the imports and such anyway. There isn't much code over there, just let them upgrade?

**Comment by jwineman** [comment]
Yeah don't worry about partners.  I'll fix when we upgrade.

**Comment by sejoker** [comment]
fixed in 3.5.1
