### ISSUE TITLE
cf-util-http doesn't convert application/json responses to JSON

### ISSUE THREAD

**Issue by hturan** [cloudflare/cf-ui#139]
In https://github.com/cloudflare/cf-ui/blob/master/packages/cf-util-http/src/http.js#L64:

```js
body: headers['content-type'] === 'application/json'
      ? JSON.parse(text)
      : text,
```

For responses with a `Content-Type: application/json; charset=UTF-8`, this will fail. We should check that the `Content-Type` header *contains* `'application/json'`.

**Comment by koddsson** [comment]
This got fixed in #141
