### ISSUE TITLE
Snapshoting generated styles (full render instead of shallow render)

### ISSUE THREAD

**Issue by tajo** [cloudflare/cf-ui#157]
We always do shallow render to test our components. So you can see changes in the DOM markup and you can see the classNames changes (styles changes). However, you can't see specific CSS rules changes. We would have to do full rendering with JSDom instead, so you have access to `<style>`. I already did it for one [test](https://github.com/cloudflare/cf-ui/blob/master/packages/cf-style-provider/test/index.js#L16).

The resulting [snapshot](https://github.com/cloudflare/cf-ui/blob/master/packages/cf-style-provider/test/__snapshots__/index.js.snap):

```
exports[`StyleProvider should render styles 1`] = `
"<!DOCTYPE html>
<html>

<head>
  <style id=\\"stylesheet\\" data-fela-stylesheet=\\"\\">
    .cf-a {
      margin: 10px
    }

    .cf-b {
      color: red
    }
  </style>
</head>

<body>
  <div id=\\"react-app\\">
    <div data-reactroot=\\"\\" class=\\"cf-a cf-b\\"></div>
  </div>

</body>

</html>"
`;
```

So this gives nice diffs even for CSS. This is more a thing for rainy day if we want to step up our testing game even more, so I'll leave it here. It would involve to abstract some of that JSDom setup and updating all current snapshot tests.

**Comment by wyuenho** [comment]
I see a good mix of shallow and deep rendering snapshots. One of the few headaches I've had was running into things that JSDOM just cannot support. Anytime we need to calculate box sizes, anything that has to do with CSS other than comparing text diffs, new (for some definition of new between now and a couple of years ago) WHATWG APIs etc.

I'd very much love to do deep snapshotting, but there's definitely some amount of work involved to mocking all these things missing from JSDOM, or removing the need to use them. Rainy day.

**Comment by koddsson** [comment]
Is this something we want to actively work on?

**Comment by tajo** [comment]
Nah. There is actually [much better way](https://github.com/rofrischmann/fela/blob/master/docs/recipes/TestingFelaComponents.md#wrap-up) how to achieve this. Closing this.
