### ISSUE TITLE
cf-component-box fontSize PropType

### ISSUE THREAD

**Issue by hturan** [cloudflare/cf-ui#170]
`cf-component-box` specifies a `number` PropType. How do I go about passing it a `'0.9rem'` size?

`cf-style-const` specifies a `px` string, which is incorrect, no?

**Comment by tajo** [comment]
The `fontSize` in `cf-style-const` is needed for things like https://polished.js.org/docs/#em. It accepts both string and number, so I guess we can do the same for `cf-component-box` ?

**Comment by jculvey** [comment]
Yeah its literally a matter of changing 

`  fontSize: {
    propType: PropTypes.number,
    default: variables.fontSize
  }`

to `  fontSize: {
    propType: numberOrString,
    default: variables.fontSize
  },`

in propertiesSpec. I'll make the change.

**Comment by hturan** [comment]
Thank youuuu!

**Comment by hturan** [comment]
@jculvey Got a PR up here: #176
