### ISSUE TITLE
cf-component-tooltip doesn't reflect changes in `content` prop

### ISSUE THREAD

**Issue by hturan** [cloudflare/cf-ui#171]
It looks like `cf-component-tooltip` reads the `content` prop once at initialization and never again, meaning that when `content` changes, the changes aren't reflected in the tooltip.

`cf-component-tooltip` should implement `componentDidUpdate` and compare props, then recreate the tooltip if changed.

**Comment by tajo** [comment]
We should rather replace it altogether if possible: https://github.com/cloudflare/cf-ui/issues/92

**Comment by hturan** [comment]
Sounds good! 😄

Can we do this when we migrate `cf-component-tooltip` to `fela`?

**Comment by hturan** [comment]
Thanks @tajo. Feel free to close this out when that lands.

**Comment by hturan** [comment]
@tajo Any update on this? Would love to get this out! Do we have plans for how we'll replace the underlying dependency? Anything I can do to help?

**Comment by tajo** [comment]
@hturan There are many even more important things to do (search for cf-ui road-plan in our wiki). However, nobody is assigned to work on cf-ui now and I can't do it in my free time.

**Comment by hturan** [comment]
@tajo Cool, no worries, I totally understand. Pushed a PR up to fix this here: #190.
