### ISSUE TITLE
Documentation doesn't show PropTypes

### ISSUE THREAD

**Issue by hturan** [cloudflare/cf-ui#174]
It looks like the new docs aren't showing PropType types:

<img width="641" alt="screen shot 2017-04-11 at 10 33 20" src="https://cloud.githubusercontent.com/assets/65447/24902537/65ef4732-1ea2-11e7-90be-b68099f3cc85.png">

Could this be to do with React 15.5 not being supported by `styleguidist`? Not sure if we're using React 15.5 for the docs, but it seems like a likely suspect.

**Comment by wyuenho** [comment]
But we haven't merged the react 15.5 PR yet?

**Comment by tajo** [comment]
Fixed now. I have no clue why that happened. I just simply rebuild and published docs again.

**Comment by tajo** [comment]
Oh, I actually know why. I was playing around with React 15.5 in `cf-styleguide` and I might to built the previous version of docs with newer React. However, `react-docgen` didn't support `prop-types` until [yesterday](https://github.com/reactjs/react-docgen/pull/172).
