### ISSUE TITLE
Layout is incorrectly displayed on styleguide

### ISSUE THREAD

**Issue by manatarms** [cloudflare/cf-ui#177]
Was looking through the styleguide and I noticed that the layout was missing the gray background boxes and the component didn't fit in it's area.
Here's a screenshot.
![page-shot-2017-4-14 cf-ui styleguide](https://cloud.githubusercontent.com/assets/4206893/25049462/d2371554-20f6-11e7-99bd-4afc6e73d86c.png)

**Comment by wyuenho** [comment]
This is a known problem. This package will be removed.
