### ISSUE TITLE
cf-component-button default style has incorrect border color

### ISSUE THREAD

**Issue by hturan** [cloudflare/cf-ui#186]
Our current cf-component-button's default grey style has a harsh dark-grey border:

<img width="162" alt="screen shot 2017-04-26 at 12 16 47" src="https://cloud.githubusercontent.com/assets/65447/25431864/3bafe506-2a7a-11e7-98b0-42fd01c593d7.png">

compared to the old style:

<img width="186" alt="screen shot 2017-04-26 at 12 17 05" src="https://cloud.githubusercontent.com/assets/65447/25431877/4b0458fc-2a7a-11e7-8a59-32967991f2fb.png">

**Comment by manatarms** [comment]
Fixed in #254 :)

**Comment by hturan** [comment]
Yay, thanks @manatarms!
