### ISSUE TITLE
Tooltip position

### ISSUE THREAD

**Issue by GDmac** [cloudflare/cf-ui#2]
First of, you guys did an amazing job on the CF-UI.
Browsing the components i noticed that tooltips can
popup on the edge. Maybe position calculation can
be based on if the tooltip content might be obscured,
rather than only when the element (button) is obscured.

http://recordit.co/VLnuvxiyP7

**Comment by thejameskyle** [comment]
Hmm, we use https://github.com/HubSpot/tooltip internally so I'll have to see if that supports something that can help

**Comment by tajo** [comment]
We will replace the underlying library by react-tooltip since HubSpot/tooltip can't server side render. https://github.com/cloudflare/cf-ui/issues/92
