### ISSUE TITLE
cloudflare.github.io/cf-ui docs text-selection not working as expected

### ISSUE THREAD

**Issue by thellimist** [cloudflare/cf-ui#202]
In the [docs](https://cloudflare.github.io/cf-ui/#cf-component-button), when selecting a text, the selection and the selected text are not the same. Single character is shifted toward left in the visual selection.

![](https://image.prntscr.com/image/9a5eca8902a6425eb06ce7e8d9650290.png)

The visual will select `<Callout title="Callout Title" content="Callout content." /` but when copied, the clipboard will be `Callout title="Callout Title" content="Callout content." />`. 

It's not possible to select the last `>` character visually. 

This bug happens in all "show source code" views

**Comment by koddsson** [comment]
Yeah I noticed that too the other day 😞

**Comment by koddsson** [comment]
Since the styleguide doesn't live in this repo tho it's probably worth filing the bug in the styleguide internal repo

**Comment by toekneestuck** [comment]
Moved internal.
