### ISSUE TITLE
Migrate `cf-component-notifications` to fela.

### ISSUE THREAD

**Issue by koddsson** [cloudflare/cf-ui#215]
Migrate the component to the CSS-in-JS framework `fela`

**Comment by manatarms** [comment]
Blocked by https://github.com/cloudflare/cf-ui/issues/334

**Comment by manatarms** [comment]
Temporary branch here. https://github.com/cloudflare/cf-ui/tree/UI-8-fela-notifications

**Comment by toekneestuck** [comment]
Moved internal.
