### ISSUE TITLE
Deprecate `cf-component-flex`

### ISSUE THREAD

**Issue by koddsson** [cloudflare/cf-ui#217]
Set a deprecation warning in npm and delete from `cf-ui`.

**Comment by hturan** [comment]
Do we need to migrate this? Can we instead deprecate it?

**Comment by koddsson** [comment]
That sounds like a swell idea to me. I basically took all the items from #100 and created separate issues from them using the API. I'll update this issue.

**Comment by hturan** [comment]
Yeah, we should totally take this opportunity to deprecate unused packages.
