### ISSUE TITLE
Migrate `cf-component-card` to fela.

### ISSUE THREAD

**Issue by koddsson** [cloudflare/cf-ui#220]
Migrate the component to the CSS-in-JS framework `fela`

**Comment by koddsson** [comment]
Note that this includes abstracting the card title into a seperate component. See https://github.com/cloudflare/cf-ui/pull/188#pullrequestreview-40581836.

**Comment by hturan** [comment]
> Note that this includes abstracting the card title into a seperate component. See #188 (review).

What about `footerMessage`? Same thing there? Are we planning on moving cf-ui from a mix of prop-driven composition models to a purely child-based JSX composition model?

**Comment by koddsson** [comment]
@hturan I think so, yeah.

**Comment by manatarms** [comment]
This seems done. Feel free to reopen if not.
