### ISSUE TITLE
Migrate `cf-component-loading` to fela

### ISSUE THREAD

**Issue by koddsson** [cloudflare/cf-ui#221]
Migrate the component to the CSS-in-JS framework `fela`

**Comment by koddsson** [comment]
I say we deprecate it. The whole component is just this snippet:

```jsx
export default class Loading extends React.Component {
  render() {
    return <Icon type="loading" label="Loading" role="status" />;
  }
}
```

**Comment by koddsson** [comment]
The team decided against deprecating. See #330 for discussion.

**Comment by koddsson** [comment]
Actually, it makes no sense to migrate this before the icon issue is done.

Blocked by: #334

**Comment by manatarms** [comment]
In review at #367
