### ISSUE TITLE
Fixed HEX codes in `cf-style-const`

### ISSUE THREAD

**Issue by koddsson** [cloudflare/cf-ui#239]
These dynamic hex values in `cf-style-const` make it extremely hard to find the color you want, we should just use the hex values.

**Comment by wyuenho** [comment]
That's what a style guide is for.

**Comment by koddsson** [comment]
What styleguide? https://cloudflare.github.io/cf-ui/ ?

**Comment by wyuenho** [comment]
No, that's an API doc inappropriately named to styleguide, a styleguide should show case the color palette, design details such as the grid system used, fonts, and sizes, illustrated by common examples of interactions among components when composed. Basically, whatever @hturan was working on.

**Comment by koddsson** [comment]
I don't think @hturan is working on anything in any official capacity (he can correct me if I'm wrong).

I think I'd much more prefer just not using the `darken(...)/lighten(...)` functions like we do now so that it's more clear what colors are declared.

**Comment by wyuenho** [comment]
Just curious, under what circumstances will you want to find a color?

**Comment by koddsson** [comment]
Sampling from other parts of the system or design and trying to find that color in `cf-style-const`.

**Comment by hturan** [comment]
> I don't think @hturan is working on anything in any official capacity (he can correct me if I'm wrong).

That's correct (although I wish it wasn't)!

---

I think this is more of a documentation issue than an implementation one.

If there was a page you could visit that visually displayed our colours, that would solve this (I think). It doesn't really matter if we implement constants as a hex-code string, an`rgba` value, or a result of a function call, since it's always going to be a valid CSS colour.

Let's add a `cf-style-const` (or something) section to our cf-ui docs that documents the package contents in a visual manner.

**Comment by wyuenho** [comment]
> If there was a page you could visit that visually displayed our colours, that would solve this (I think). 

Yes. I think I was referring to the styleguide-audit project you were working on in unofficial capacity

**Comment by koddsson** [comment]
So move this to the `cf-styleguide` project?

**Comment by koddsson** [comment]
What's going to happen here? Is someone going to add documentation to `cf-styleguide`?

**Comment by manatarms** [comment]
I'm working on adding documentation to cf-styleguide for colors and icons.

**Comment by wyuenho** [comment]
@mrmrs You may want to coordinate with the people here.

**Comment by mrmrs** [comment]
@manatarms Where is the info coming from that you are adding to the documentation re: colors?

**Comment by manatarms** [comment]
@mrmrs PMed you for extended convo.

**Comment by koddsson** [comment]
I still feel like this isn't as much a thing any more.
