### ISSUE TITLE
Remove all traces of findDOMNode

### ISSUE THREAD

**Issue by wyuenho** [cloudflare/cf-ui#24]
`findDOMNode` is going to be deprecated, so we have to remove them.

https://github.com/yannickcr/eslint-plugin-react/issues/678#issue-165177220

**Comment by wyuenho** [comment]
The only one left is in Tooltip. Will remove it when React removes findDOMNode

**Comment by koddsson** [comment]
Is this issue waiting for some event from the react team to be finished?

**Comment by toekneestuck** [comment]
Moved internal.
