### ISSUE TITLE
Performance metrics of smart CSS in JS

### ISSUE THREAD

**Issue by degroote22** [cloudflare/cf-ui#249]
Hey guys.
First of all I'd like to give a thumbs up for your idea to implement a UI kit on one of those new "smart" (atomic classes, etc) CSS in JS solutions.
But I've never seen what are the real gains this approach brings.
Have you done some kind of benchmarking related to this issue that you'd be willing to share? (Overall css size, painting time, etc)
Thanks for your time.

**Comment by tajo** [comment]
There are some benchmarks comparing CSS in JS solutions and many articles why to use /  not to use CSS in JS in general. I would say that the real gain is our developer experience. Fela (our CSS in JS solution) is using `<style></style>` not inline-styles, so there is no performance hit or limitations compare to CSS, because it is CSS.

**Comment by wyuenho** [comment]
We should/will blog about this at some point. We are still very early in the process of migrating towards a CSS-in-JS solution that fits our requirements. At some point we'll talk about why we chose Fela and why we think it's a far superior solution than any existing solution.

**Comment by mrmrs** [comment]
Can't speak to the specifics of Fela or the context of these components but from a css rendering performance standpoint - css in js allows to only send styles needed for a view down the wire. The average website only uses ~2% of downloaded css per view. Additionally as the styles are inlined into a style tag there is no http request which is a huge perf savings. Other benefits are that long selectors can have non-trivial impacts on rendering / paint time and this pattern promotes keeping selectors short and keeping rendering / paint times fast.

**Comment by koddsson** [comment]
To answer the original question @degroote22, we haven't done any metrics so far and it's not on any roadmap I've seen. 

If we do end up doing some metrics/benchmarking we'll add that information to this repo :)

Feel free to re-open this issue if you wanna know more.
