### ISSUE TITLE
[Question] Query regarding the approach taken for styleguide

### ISSUE THREAD

**Issue by aga5tya** [cloudflare/cf-ui#250]
First off kudos to wonderful UI framework, inspired by the approach i'm implementing in a similar way but has very few components used internally, using fela ofcourse. I would like your help in figuring out the direction taken for the styleguide generation. I have given my shot at react-styleguidist, but unable to achieve what i intend to.

Have raised an issue (styleguidist/react-styleguidist#478) with a sample repo. I understand its internal but, any pointers you guys provide will highly help me with the issue i am facing

**Comment by koddsson** [comment]
Hey @aga5tya, we aren't using `react-stylegudist`, but rather a internal product to serve as a stylegude, so we'd be unable to help you with that 🙁

**Comment by jwineman** [comment]
You can look at the [GitHub page for this repository](https://cloudflare.github.io/cf-ui/) to see how we integrated Fela into our public style guide as well.  If you have questions about our implementation we're happy to answer them!

**Comment by tajo** [comment]
You can checkout @koddsson's [PR](https://github.com/cloudflare/cf-ui/pull/145/files) that was integrating styleguidist (mostly successfully?) and also some discussion why it didn't land. I think it's a great tool and I recommend to use it (if you overcome the issues you have). I just think that we can go much further without it.

I think we will eventually open-source some of our internal tooling when the time is right but it's too tied to our projects and needs a lot of work.

**Comment by aga5tya** [comment]
@tajo, @jwineman, @koddsson , 
Thank you so much guys for helping me out in pointing me with the direction. 

@koddsson, your PR really helped alot, Cheers man!. :beers:
