### ISSUE TITLE
Rename cf-style-container

### ISSUE THREAD

**Issue by wyuenho** [cloudflare/cf-ui#253]
The reasons for this name is completely lost on me, but since it's more of a util or tools package, can we rename this so it better reflects what this package does? It doesn't "contain" anything.

**Comment by tajo** [comment]
> The reasons for this name is completely lost on me

It didn't have a clear purpose when it was created. Also, cf-style-provider didn't exist at that time.

I like `cf-style-tools`, following example of [fela-tools](https://github.com/rofrischmann/fela/tree/master/packages/fela-tools)

**Comment by toekneestuck** [comment]
Moved internal.
