### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by wyuenho** [cloudflare/cf-ui#29]
@jwineman said he wanted to get CI up and running. Travis should help with linting, but if we could set up saucelabs to run tests in many different browsers, that'll be really nice.

**Comment by koddsson** [comment]
I was gonna take a stab at this but I need admin rights to enable it in Travis. Could someone either tick the box in travis or give me admin rights?

**Comment by jwineman** [comment]
I tried to enable Travis and also don't have sufficient access.   @terinjokes can you enable please?

**Comment by terinjokes** [comment]
OK
