### ISSUE TITLE
Missing cf-component-viewport and flex

### ISSUE THREAD

**Issue by tajo** [cloudflare/cf-ui#337]
We use cf-component-flex [here](https://github.com/cloudflare/cf-ui/blob/master/packages/cf-component-form/example/basic/component.js#L10) and cf-component-viewport [here](https://github.com/cloudflare/cf-ui/blob/master/packages/cf-component-tabs/src/Tabs.js#L3). They were both deleted and deprecated.

It would be great to remove them. Especially in cf-component-tabs since it's a part of the package. What do you think @koddsson?

**Comment by tajo** [comment]
missing `cf-component-flex` actually breaks styleguide now

**Comment by koddsson** [comment]
>missing cf-component-flex actually breaks styleguide now

I think I got it working by rebuilding everything in `cf-ui`

**Comment by koddsson** [comment]
>It would be great to remove them. Especially in cf-component-tabs since it's a part of the package. What do you think @koddsson?

Yeah, I think that's definitely the next steps.

**Comment by toekneestuck** [comment]
Moving internal.
