### ISSUE TITLE
cf-component-button has a required onClick prop

### ISSUE THREAD

**Issue by koddsson** [cloudflare/cf-ui#34]
I wanted to make a submit button but I keep getting errors because it wants a `onClick`.

**Comment by koddsson** [comment]
nvm

**Comment by jwineman** [comment]
What was the solution?

**Comment by koddsson** [comment]
I was having troubles combining `cf-component-modal` and `redux-forms` since the submit button was going into the `<ModalFooter />` component and not in the form itself. The solution was to call submit directly in the super component.
