### ISSUE TITLE
Fix drop down top arrow 

### ISSUE THREAD

**Issue by manatarms** [cloudflare/cf-ui#368]
Some very minor style feedback:

    The popover arrow is missing a shadow.
    The popover border should be implemented as a black shadow with opacity rather than an opaque grey border.
![image](https://user-images.githubusercontent.com/4206893/30140849-45edaa74-932c-11e7-80e4-75307e32372b.png)
![image1](https://user-images.githubusercontent.com/4206893/30140848-45e8aac4-932c-11e7-864b-df43ebbac262.png)

For both 1. and 2. see my original https://codepen.io/adamschwartz/pen/mMQqvp for an example implementation which handles both of these properly.

**Comment by toekneestuck** [comment]
Moved internal.
