### ISSUE TITLE
Import strategy in your main applications

### ISSUE THREAD

**Issue by SpencerCDixon** [cloudflare/cf-ui#381]
First, wanted to say thank you for open sourcing this UI kit.  I've enjoyed reading your discussion docs and have learned a lot.  I'm about to embark on building a similar project and had a few questions:

1.  Does the import strategy get annoying in your applications that use the UI kit?  For example:

```
import Button from 'cf-button';
import Card from 'cf-card';
import Icon from 'cf-icon';
```
Opposed to:
```
import { Button, Card, Icon } from 'cf-ui';
```

2.  Do you have components that are not published openly in the UI kit?

3.  Could one potentially build their applications alongside the UI kit as a separate private package?  I imagine the context switching between the UI kit and main application can get somewhat frustrating, yeah?

**Comment by SpencerCDixon** [comment]
@tajo any thoughts?  Also how do you guys do development of the components?  Do you have a package that runs a webpack server to test everything out?

**Comment by tajo** [comment]
@SpencerCDixon 

1. Not at all. Having a single entry point `cf-ui` would not scale when you start counting modules in hundreds. Various components can export `Button` without need to use some prefixes as `DropdownButton`, `PaginationButton`.

2. Yes!

3. You can place your application into the same `yarn workspace` as your UI kit. Everything gets symlinked. You can even take it a step further and alias all package imports through babel, so when you are deving, there is not difference between "main" code and UI kit code.

> Also how do you guys do development of the components? Do you have a package that runs a webpack server to test everything out?

Yes, we have a special app that serves as a "canvas" for developing components in isolation. We also have a command to alias source of these components into our main application, so we can tweak it there as well.

**Comment by SpencerCDixon** [comment]
Sweeeeet, thank you for answering all my questions!  I've been using this setup for the past couple months now and am really enjoying it.  I've even been able to publish and reuse some form/util packages between web and react native.  

The separate packages for importing has been pivotal for keeping bundle sizes small when code splitting!

Thanks again for the inspiration 

Cheers 🍻 

Edit: for others curious I set up styleguidist for component development/documentation and I have my web app in the `packages` dir as `web` and it's a private package
