### ISSUE TITLE
Upgrade superagent

### ISSUE THREAD

**Issue by wyuenho** [cloudflare/cf-ui#67]
We are using superagent 1.x in cf-util-http, superagent is at 3.x now. Should probably upgrade before it's too late.

**Comment by jwineman** [comment]
This is kind of frustrating because Jest swallows `console.log()` if the test errors out.  Since sinon's fake server is failing _inside_ the test itself its hard to tell whats broken.

**Comment by tajo** [comment]
Superagent replaced by fetch.
