### ISSUE TITLE
Deprecate cf-component-viewport

### ISSUE THREAD

**Issue by wyuenho** [cloudflare/cf-ui#68]
We haven't found much use of it and it's not particularly performant. Media queries are best dealt with via either a style sheet or some css-in-js solution.

**Comment by jwineman** [comment]
> We haven't found much use of it
To clarify - do we use this a few times or not at all?

**Comment by tajo** [comment]
Why is not useful?

**Comment by wyuenho** [comment]
We are only using cf-component-viewport in cf-component-tabs, but it's not necessary. cf-component-viewport assumes different DOM structures based on different media sizes. The sizes are also hardcoded in ems and cannot be changed. All this suggests this component isn't general purpose, we can't use it for the modals or cards.

I think there are definitely occasional uses for `window.matchQuery` but that should be used as [element queries](http://casesandberg.github.io/react-bounds/). Elements should resize based on how much space is available to them on the parent instead of some proxy of it determined by the viewport size.

For element queries, react-bounds or react-element-query are probably much better options.

**Comment by toekneestuck** [comment]
Moved internal.
