### ISSUE TITLE
cf-test-server has almost the same README.md as cf-test-store

### ISSUE THREAD

**Issue by bugron** [cloudflare/cf-ui#7]
Compare [cf-test-server's README.md](https://github.com/cloudflare/cf-ui/blob/master/packages/cf-test-server/README.md) with [cf-test-store's README.md](https://github.com/cloudflare/cf-ui/blob/master/packages/cf-test-store/README.md). Seems this is just another copy-paste issue.

**Comment by thejameskyle** [comment]
heh, thats funny

**Comment by thejameskyle** [comment]
Fixed

**Comment by bugron** [comment]
:+1:
