### ISSUE TITLE
Inconsistancy between cf-component-input example website and master

### ISSUE THREAD

**Issue by manatarms** [cloudflare/cf-ui#74]
I noticed that the cf-component-input on the example website is out of date. Specifically the ` handleChange` and `constructor` functions. 
The master build however, shows the correct example. Not sure if this is something to do with a  publishing issue. 

https://cloudflare.github.io/cf-ui/#cf-component-input

https://github.com/cloudflare/cf-ui/blob/master/packages/cf-component-input/example/basic/component.js

**Comment by jwineman** [comment]
I'm assuming the build diffs the current example site vs the one in production and doesn't deploy if they're the same.  Its possible someone didn't run `npm run examples:build:internal` before `npm run publish`.

**Comment by wyuenho** [comment]
We haven't updated the gh-pages branch for a while.
