### ISSUE TITLE
Need default values for IE in cf-component-flex

### ISSUE THREAD

**Issue by wyuenho** [cloudflare/cf-ui#76]
Because of this:

https://github.com/philipwalton/flexbugs

**Comment by sejoker** [comment]
@wyuenho do you reference to [this bug](https://github.com/philipwalton/flexbugs#6-the-default-flex-value-has-changed)? If so it was fixed in IE 11, we don't support IE 10, could be closed :)

**Comment by wyuenho** [comment]
This is no longer relevant to us, I think we've reached a breaking point where everyone just wants to remove cf-component-flex. Flexbox properties are designed so that we can attach non-flexbox properties onto the same div, otherwise we'll contract divititus. Using a whitelist approach, we simply can't do it. If we allow arbitrary style props to be passed in, the end result will be exactly the same as using a div directly, or using fela's createComponent(). There's no point for cf-component-flex's existence. We should leave higher level layouts to the users, and style larger cf-component composites with some conceptual grid system that's responsive, which should be left to the designers to help us out.

CC. @jwineman @jculvey @koddsson @hturan @tajo @marksteyn
