### ISSUE TITLE
Missing react-fela in `cf-component-button` 4.0.0

### ISSUE THREAD

**Issue by koddsson** [cloudflare/cf-ui#82]
This code:

```js
import React from 'react';
import {render} from 'react-dom';
import {Button} from 'cf-component-button';

const App = () => {
  return <Button>Click me</Button>
}

render(<App />, document.querySelector('body'));
```

results in this error
`stderr: Error: Cannot find module 'react-fela' from '/tmp/cf-component-button117127-29294-18e4ou5/node_modules/cf-component-button/node_modules/cf-style-container/lib'`

**Comment by koddsson** [comment]
@tajo Do you know how we can fix this?

**Comment by hturan** [comment]
It looks like all of our `cf-component-button` tests were commented out as part of #77, meaning this wasn't caught in CI.

**Comment by tajo** [comment]
Solved with https://github.com/cloudflare/cf-ui/pull/91
