### ISSUE TITLE
Change activeTab to active in cf tabs component

### ISSUE THREAD

**Issue by manatarms** [cloudflare/cf-ui#83]
Creating this issue to track the PR for moving to active from activeTab prop in the cf-component-tabs package.

So far I've only found the following use of activeTab in www-next.
1) containers/analytics/billboard/RateLimitingCard.js:

**Comment by wyuenho** [comment]
This is fixed right?

**Comment by jwineman** [comment]
Yea in

**Comment by manatarms** [comment]
Yup. It's fixed but to keep the props consistent we're renaming the activeTab prop to active. This will break stuff so releasing it as a major change.

**Comment by jwineman** [comment]
Closing since the PR is merged. @manatarms knows how to find the affected components when he bumps the version after it gets released.
