### ISSUE TITLE
Missing prop types descriptions in docs

### ISSUE THREAD

**Issue by manatarms** [cloudflare/cf-ui#89]
The prop type descriptions are missing from the README files of individual packages and also on the external example websites. Actual src in packages is fine, just the docs are missing the prop descriptions.

The descriptions should be below the example, but theyre not. See screenshot.
![page-shot-2017-2-28 cloudflare components](https://cloud.githubusercontent.com/assets/4206893/23440669/42d484ba-fdd2-11e6-962b-e244183c7970.png)

**Comment by tajo** [comment]
I'm completely rewriting example generator and pretty much everything regarding the build (removing gulp). I'll fix this sooner or later.
