### ISSUE TITLE
cf-component-tooltip can't be server-side rendered

### ISSUE THREAD

**Issue by tajo** [cloudflare/cf-ui#92]
It uses "tether-tooltip" and that library touches DOM all over the place. The new styleguide is going to be server-side rendered so this is breaking my styleguide build currently. I'm going to remove it from the styleguide and we should replace "tether-tooltip" with something better. 

[react-tooltip](https://github.com/wwayne/react-tooltip) looks pretty good and we could preserve similar (same?) API.

I tried many hacks and tricks how to bypass it on server but it's not worth of effort just because of one single component.

**In general, all our cf-ui component should be compatible with server side rendering.**

**Comment by sejoker** [comment]
I used react-tooltip in the past without any issues. The app supported server-side rendered.

**Comment by koddsson** [comment]
Is this a think we want to work on?

I don't think server-side rendering is actively being worked in the team for now so I'd like to focus more on stuff we are actually going to do and bring this back up later if we ever wanna do server side rendering.

Ok if I close this with maybe a label of "Possible future work" so it's easy to find again later?

**Comment by tajo** [comment]
> Is this a think we want to work on?

**Yes.** 

We already use server-side rendered cf-ui components for [api docs](https://api.cloudflare.com) and [styleguide](https://cloudflare.github.io/cf-ui/). So this is a blocker preventing us to use cf-component-tooltip in both of these projects. **There is no excuse to throw server-side compatibility out of the window**.

**Comment by koddsson** [comment]
I mean the argument could be made that we're spending time on issues like this where we are making sure that we are able to server-side rendering even though we don't use it in the dashboard. I'd argue that we aren't throwing it out the window but rather just not taking up time implementing it when we aren't really using it.

Why are we server-side rendering in the styleguide and api docs?

**Comment by tajo** [comment]
> taking up time implementing it 

It doesn't really take an extra time. It's just not doing bad things in our components (using global stuff as `window` etc).

> Why are we server-side rendering in the styleguide and api docs?

- **faster loader time**, the page doesn't wait for JS bundle, parsing, executing...
- better for search engines
- we could ship docs without JavaScript and it would still work pretty good

**Comment by koddsson** [comment]
Is this being worked on or is this just a feature request for the future?

**Comment by toekneestuck** [comment]
Moved internal.
