### ISSUE TITLE
Fix flaky test for cf-component-notifications

### ISSUE THREAD

**Issue by tajo** [cloudflare/cf-ui#96]

**Comment by tajo** [comment]
It seems to be stable now.

**Comment by sejoker** [comment]
@tajo I don't think so

**Comment by tajo** [comment]
Ok, I'll keep an eye on it.

**Comment by wyuenho** [comment]
This appears to be related to the timers, should probably look into what [jest has to offer](https://facebook.github.io/jest/docs/jest-object.html#content) so we can trigger the callback backs deterministically.

**Comment by sejoker** [comment]
fixed #154
