### ISSUE TITLE
Deciding the fate of Link component

### ISSUE THREAD

**Issue by manatarms** [cloudflare/cf-ui#99]
**Current Situation**
I was migrating ```cf-component-link``` to Fela and noticed that we have a dual implementation in the component. So I have some questions about how we want this component to behave.

Currently, the component accepts a ```tagName``` that is rendered instead of `<a></a>`. The component also accepts a ```to``` prop that is used to route to a location. 

I've noticed use cases of  ```cf-component-link``` where _"link should look like a link but act like a button"_. 

The ```tagName``` and ```to``` props introduce quite a few ```if``` statements into the component. These statements check for ```href```, ```onClick```, ```to``` and call different functions accordingly. This also diverges from the idea of having a standardized component library by allowing a user to render anything as a link using the ```tagName``` prop. 

**Questions**

1. Should we remove the ability to make anything a link? i.e. Always render an ```<a>{children}</a>```
2. Should we remove the ```{to}``` entirely and have just an onClick handler. This will satisfy the button use case. The routing can also then be handled using the onClick handler. 
OR
3. Should we keep the ```{to}``` and remove the ability to call a custom onClick handler. This will force users to restyle the cf-component-button to look like a link (which would now be super easy using Fela). Routing can then be handled using the ```to``` prop.
4. 
![marilee-ullmann-quote-we-love-it-the-way-it-is-its-not-broken-dont-fix](https://cloud.githubusercontent.com/assets/4206893/24019708/5834382e-0a56-11e7-9416-17a7a92193d0.jpeg)

**Comment by jwineman** [comment]
I'm pretty sure we stole the `<Link to={PAGE}/>` interface from React Router.  I'd prefer `<Link onClick={}/>` and have us pass in a bound action creator from react router with the link OR any random function if we want it to behave like a button or whatever.

**Comment by sejoker** [comment]
I think it was designed with this flexibility in mind. What are pain points we have with current implementation?

**Comment by jwineman** [comment]
Implementing `to` couples it to whatever router we're using.  Since `to` and `onChange` both usually end up calling redux actions we can probably consolidate.

**Comment by manatarms** [comment]
With current implementation in order for Fela to accept our onClick handler we need to change the handler before passing it to Fela. Which goes against React philosophy of never changing props.

**Comment by wyuenho** [comment]
So far, nobody has used `<Link>` for anything other than an anchor. I suspect the way it is now is because we have styles that render buttons that look like links. I'm also not sure what the exactly @manatarms means by having to change the handler. It's already wrapped by `handleClick()` ? `onClick` has nothing to do with styling at all, why does Fela need to know about it?

**Comment by jwineman** [comment]
It doesn't have anything to do with Fela.  The old interface allowed `to` and `onClick` but `to` is only useful if you're getting that component from a routing library.  We're going to consolidate down to `onClick` and if you need to use `<Link/>` with react router etc then you need to pass in the action `to` would have called.

**Comment by koddsson** [comment]
Is something we want to do here?

**Comment by koddsson** [comment]
I'm inclined to close this if this conversation has kind of fizzled out and there is no clear path to take to do anything, would that be fair @manatarms ?

**Comment by manatarms** [comment]
Totally fair @koddsson. Closed because irrelevant now.

**Comment by koddsson** [comment]
Nice! Thanks for that, I'm trying to keep the issues neat and tidy so it reflects what work we are actually doing.
